name: meshroom-local

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASSWORD:-pass}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - meshroom

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meshroom

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meshroom-api
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - meshroom

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - meshroom-workspace:/var/lib/meshroom
    command: python -m app.worker
    networks:
      - meshroom
    deploy:
      replicas: 2

volumes:
  rabbitmq-data:
  minio-data:
  meshroom-workspace:

networks:
  meshroom:
    driver: bridge