name: 3d-reconstruction-local

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - 3d-reconstruction

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - 3d-reconstruction

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3d-reconstruction-api
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - 3d-reconstruction

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/service
      - meshroom-workspace:/var/lib/meshroom
    command: python -m app.worker
    networks:
      - 3d-reconstruction
    deploy:
      replicas: 1

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3d-reconstruction-flower
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5555:5555"
    volumes:
      - .:/service
    command: celery -A app.celery_app flower --port=5555
    networks:
      - 3d-reconstruction

volumes:
  redis-data:
  minio-data:
  meshroom-workspace:

networks:
  3d-reconstruction:
    driver: bridge