name: meshroom-production

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - meshroom

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meshroom-api
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    networks:
      - meshroom

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - meshroom-workspace:/var/lib/meshroom
    command: python -m app.worker
    networks:
      - meshroom
    deploy:
      replicas: 4

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meshroom-flower
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: celery -A app.celery_app flower --port=5555
    networks:
      - meshroom

volumes:
  redis-data:
  meshroom-workspace:

networks:
  meshroom:
    driver: bridge
