from pathlib import Path
import subprocess
from typing import Any

from app.core.logger import Logger
from app.core.settings import MeshroomConfigModel
from app.core.reconstruction.base import BaseReconstructProvider


class MeshroomReconstructProvider(BaseReconstructProvider):
    provider_code = 'meshroom'

    def __init__(
        self,
        input_dir: str | None = None,
        output_dir: str | None = None,
        cache_dir: str | None = None,
        logger: Logger | None = None,
        config: MeshroomConfigModel | None = None,
    ):
        super().__init__(input_dir, output_dir, cache_dir, logger, config)

    async def process(self, *args: Any, **kwargs: Any) -> str:
        """Process the reconstruction and return path to GLB file."""
        input_dir = Path(self.input_dir)
        output_dir = Path(self.output_dir)
        cache_dir = Path(self.cache_dir) if self.cache_dir else None

        # 1️⃣ Создаём выходную папку
        output_dir.mkdir(parents=True, exist_ok=True)

        # 2️⃣ Запуск AliceVision_photogrammetry
        cmd_av = [
            self.config.binary or "aliceVision_photogrammetry",
            "--input", str(input_dir),
            "--output", str(output_dir),
        ]
        if cache_dir:
            cmd_av.extend(["--cache", str(cache_dir)])
        
        if self.logger:
            self.logger.info(f"Running AliceVision: {' '.join(cmd_av)}")

        subprocess.run(cmd_av, check=True)
        obj_files = list(output_dir.glob("*.obj"))
        if not obj_files:
            raise RuntimeError("No OBJ file generated by AliceVision.")

        obj_path = obj_files[0]
        glb_path = output_dir / f"{obj_path.stem}.glb"

        # 4️⃣ Конвертация OBJ → GLB с текстурами через obj2gltf
        cmd_glb = [
            "obj2gltf",
            "-i", str(obj_path),
            "-o", str(glb_path),
            "-b"  # встроить текстуры в GLB
        ]
        if self.logger:
            self.logger.info(f"Converting to GLB: {' '.join(cmd_glb)}")

        subprocess.run(cmd_glb, check=True)

        if self.logger:
            self.logger.info(f"GLB file ready: {glb_path}")

        return str(glb_path)
